base: &base
  adapter: mysql
  timeout: 5000
  encoding: utf8

development:
  database: notlr_development
  username: root
  password:
  <<: *base

production:
  database: notlr_test
  username: root
  password:
  <<: *base

test:
  database: notlr_test
  username: root
  password:
  <<: *base
